language: php

php:
  - 5.6
  - 7.0
  - 7.1

before_install:
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - composer install
  - composer require satooshi/php-coveralls --dev

script:
  - vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
